### ISSUE TITLE
deviceTokens have incorrect length

### ISSUE THREAD

**Issue by ligerjohn** [reachlocal/liger-ios#99]
deviceToken bytes smaller than 10 doesn't get a trailing 0 and thus the deviceToken is too short.

**Comment by tonyc** [comment]
I found a much, much simpler way to get the device token. Check out this code:

https://github.com/phonegap-build/PushPlugin/blob/master/src/ios/PushPlugin.m#L148-L151

**Comment by ligerjohn** [comment]
Using describe seems to be one of the more common ways of doing this. At least one of the more suggested. The downside is that it's using the output of a debug method (describe) which Apple doesn't guarantee the output of , so it's neither recommended nor safe.

Using stringByAppendingFormat is more future (and swift) compatible.
